name: my_site
title: [The title of my site]
description: [A short description of my site's purpose]
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
